AaxisTest/src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use DateTime;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50, unique:true)]
    private ?string $sku = null;

    #[ORM\Column(length: 250)]
    private ?string $product_name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $update_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getSku(): ?string
    {
        return $this->sku;
    }

    public function setSku(string $sku): static
    {
        $this->sku = $sku;

        return $this;
    }

    public function getProductName(): ?string
    {
        return $this->product_name;
    }

    public function setProductName(string $product_name): static
    {
        $this->product_name = $product_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    public function updatedTimestamps(): void
    {
        $dateTimeNow = new DateTime('now');

        $this->setUpdateAt($dateTimeNow);

        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt($dateTimeNow);
        }
    }
}

AaxisTest/src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('sku')
            ->add('product_name')
            ->add('description')
            ->add('created_at')
            ->add('update_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

AaxisTest/src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use PhpParser\Node\Stmt\TryCatch;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use DateTime;
use Symfony\Component\Validator\Constraints\Length;

#[Route('/product')]
class ProductController extends AbstractController
{

    private $productRepository;

    public function __construct(ProductRepository $productRepository)
    {
        $this->productRepository = $productRepository;
    }
    #[Route('/', methods: ['GET'])]
    public function getAll(): JsonResponse
    {
        try {
            $products = $this->productRepository->findAll();
            $data = [];

            foreach ($products as $product) {
                $data[] = [
                    'id' => $product->getId(),
                    'sku' => $product->getSku(),
                    'name' => $product->getProductName(),
                    'description' => $product->getDescription(),
                    'created_at' => $product->getCreatedAt()->format('Y-m-d H:i:s'), // Format the datetime
                    'updated_at' => $product->getUpdateAt()->format('Y-m-d H:i:s'), // Format the datetime
                ];
            }

            return new JsonResponse($data, Response::HTTP_OK);
        } catch (\Exception $e) {
            return new JsonResponse(['error' => 'Error ocurrido'], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    #[Route('/add', methods: ['POST'])]
    public function new(Request $request): JsonResponse
    {
        try {
            $data = json_decode($request->getContent(), true);

            if (!is_array($data) || empty($data)) {
                throw new \InvalidArgumentException('La solicitud debe contener un arreglo de productos.');
            }

            $createdProducts = [];
            foreach ($data as $productData) {
                $sku = $productData['sku'];
                $name = $productData['name'];
                $description = $productData['description'] ?? null;

                if (empty($sku) || empty($name)) {
                    throw new \InvalidArgumentException('Faltan parámetros, sku y name son obligatorios.');
                }
                $product = new Product();
                $product->setSku($sku);
                $product->setProductName($name);
                $product->setDescription($description);
                $currentDateTime = new \DateTime('now', new \DateTimeZone('America/Santiago'));
                $product->setCreatedAt($currentDateTime);
                $product->setUpdateAt($currentDateTime);

                $this->productRepository->saveProduct($product);

                $createdProducts[] = [
                    'id' => $product->getId(),
                    'sku' => $product->getSku(),
                    'name' => $product->getProductName(),
                    'description' => $product->getDescription(),
                    'created_at' => $product->getCreatedAt()->format('Y-m-d H:i:s'),
                    'updated_at' => $product->getUpdateAt()->format('Y-m-d H:i:s'),
                ];
            }
            return new JsonResponse(['status' => 'Productos creados!', 'created_products' => $createdProducts], Response::HTTP_CREATED);
        } catch (\Exception $e) {
            return new JsonResponse(['error' => 'Error ocurrido: ' . $e->getMessage()], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }
    #[Route('/update', methods: ['PUT'])]
    public function update(Request $request): JsonResponse
    {
        try {
            $data = json_decode($request->getContent(), true);
    
            if (!is_array($data) || empty($data)) {
                throw new \InvalidArgumentException('La solicitud debe contener un arreglo de productos a actualizar.');
            }
    
            $updatedProducts = [];
    
            foreach ($data as $productData) {
                $sku = $productData['sku'] ?? null;
                $name = $productData['name'] ?? null;
                $description = $productData['description'] ?? null;
    
                if (empty($sku) || !is_string($sku)) {
                    throw new \InvalidArgumentException('Cada producto debe tener al menos la clave "sku".');
                }
    
                $product = $this->productRepository->findOneBy(['sku' => $sku]);
    
                if (!$product) {
                    throw new \RuntimeException('Producto con SKU ' . $sku . ' no encontrado.');
                }
    
                if (!empty($name)) {
                    $product->setProductName($name);
                }
    
                if (!empty($description)) {
                    $product->setDescription($description);
                }
    
                $this->productRepository->updateProducts($product);
    
                $updatedProducts[] = [
                    'sku' => $product->getSku(),
                    'name' => $product->getProductName(),
                    'description' => $product->getDescription(),
                ];
            }
    
            return new JsonResponse(['status' => 'Productos actualizados.', 'updated_products' => $updatedProducts], JsonResponse::HTTP_OK);
        } catch (\Throwable $e) {
            return new JsonResponse(['error' => 'Error ocurrido: ' . $e->getMessage()], JsonResponse::HTTP_INTERNAL_SERVER_ERROR);
        }
    }
    
    #[Route('/delete/{sku}', methods: ['DELETE'])]
    public function delete($sku): JsonResponse
    {
       try {
            $product = $this->productRepository->findOneBy(['sku' => $sku]);
            $this->productRepository->removeProduct($product);

            return new JsonResponse(['status' => 'Producto eliminado','producto eliminado con sku' => $sku], JsonResponse::HTTP_OK);
        } catch (\Throwable $e) {
            return new JsonResponse(['error' => 'Error ocurrido: ' . $e->getMessage()], JsonResponse::HTTP_INTERNAL_SERVER_ERROR);
            
       }
    }
}

AaxisTest/templates/product/_delete_form.html.twig
<form method="post" action="{{ path('app_product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn">Delete</button>
</form>

AaxisTest/templates/product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

AaxisTest/templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <h1>Edit Product</h1>

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_product_index') }}">back to list</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}

AaxisTest/templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product index{% endblock %}

{% block body %}
    <h1>Product index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Sku</th>
                <th>Product_name</th>
                <th>Description</th>
                <th>Created_at</th>
                <th>Update_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ product.sku }}</td>
                <td>{{ product.productName }}</td>
                <td>{{ product.description }}</td>
                <td>{{ product.createdAt ? product.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ product.updateAt ? product.updateAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_product_show', {'id': product.id}) }}">show</a>
                    <a href="{{ path('app_product_edit', {'id': product.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_product_new') }}">Create new</a>
{% endblock %}

AaxisTest/templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <h1>Create new Product</h1>

    {{ include('product/_form.html.twig') }}

    <a href="{{ path('app_product_index') }}">back to list</a>
{% endblock %}

AaxisTest/templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
    <h1>Product</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ product.id }}</td>
            </tr>
            <tr>
                <th>Sku</th>
                <td>{{ product.sku }}</td>
            </tr>
            <tr>
                <th>Product_name</th>
                <td>{{ product.productName }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ product.description }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ product.createdAt ? product.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Update_at</th>
                <td>{{ product.updateAt ? product.updateAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_product_index') }}">back to list</a>

    <a href="{{ path('app_product_edit', {'id': product.id}) }}">edit</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}